# Generated by Django 2.1.5 on 2020-12-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Netfeelex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre_filme', models.CharField(max_length=200)),
                ('Contenu_filme', models.TextField()),
                ('Date_publie', models.DateField(verbose_name='Date publie')),
            ],
        ),
    ]
